-- Test-only tooling. Its lockfile pins the grammars and matching queries.
return {
  tooling_revision = '42fc28ba918343ebfd5565147a42a26580579482',
  cli_version = '0.25.10',
  languages = {
    'astro',
    'bash',
    'c',
    'css',
    'dockerfile',
    'fish',
    'html',
    'java',
    'javascript',
    'json',
    'kotlin',
    'lua',
    'markdown',
    'markdown_inline',
    'nix',
    'php',
    'python',
    'ruby',
    'scss',
    'sql',
    'swift',
    'toml',
    'typescript',
    'vim',
    'yaml',
  },
}
